import { Category } from "@/types/main";

const GERMANY: Category = {
  name: "Германия",
  items: [
    // Легко
    { name: "Берлин", level: "easy" },
    { name: "Октоберфест", level: "easy" },
    { name: "Шницель", level: "easy" },
    { name: "Пиво", level: "easy" },
    { name: "Гитлер", level: "easy" },
    { name: "БМВ", level: "easy" },
    { name: "Ауди", level: "easy" },
    { name: "Мерседес", level: "easy" },
    { name: "Порше", level: "easy" },
    { name: "Немецкая овчарка", level: "easy" },
    { name: "Университет", level: "easy" },
    { name: "Школа", level: "easy" },
    { name: "Дождь", level: "easy" },
    { name: "Снег", level: "easy" },
    { name: "Холод", level: "easy" },
    { name: "Паспорт", level: "easy" },
    { name: "ВНЖ", level: "easy" },
    { name: "Банк", level: "easy" },
    { name: "Супермаркет", level: "easy" },
    { name: "Лидл", level: "easy" },
    { name: "Альди", level: "easy" },
    { name: "DM", level: "easy" },
    { name: "Rossmann", level: "easy" },
    { name: "Аптека", level: "easy" },
    { name: "Врач", level: "easy" },
    { name: "Поезд", level: "easy" },
    { name: "Станция", level: "easy" },
    { name: "Часы", level: "easy" },
    { name: "Озеро", level: "easy" },
    { name: "Парк", level: "easy" },
    { name: "Горы", level: "easy" },
    { name: "Лес", level: "easy" },
    { name: "Цветы", level: "easy" },
    { name: "Солнышко", level: "easy" },
    { name: "Тюльпаны", level: "easy" },
    { name: "Облака", level: "easy" },
    { name: "Документы", level: "easy" },
    { name: "Курсы", level: "easy" },
    { name: "Виза", level: "easy" },
    { name: "Беженец", level: "easy" },
    { name: "Мигрант", level: "easy" },
    { name: "Билет", level: "easy" },
    { name: "Метро", level: "easy" },
    { name: "Велосипед", level: "easy" },
    { name: "Пластик", level: "easy" },
    { name: "Возврат бутылок", level: "easy" },
    { name: "Пособие", level: "easy" },
    { name: "Бумаги", level: "easy" },
    { name: "Евро", level: "easy" },
    { name: "История", level: "easy" },

    // Средне
    { name: "Бундестаг", level: "medium" },
    { name: "Бавария", level: "medium" },
    { name: "Бранденбургские ворота", level: "medium" },
    { name: "Мюнхен", level: "medium" },
    { name: "Франкфурт", level: "medium" },
    { name: "Гамбург", level: "medium" },
    { name: "Ганновер", level: "medium" },
    { name: "Кёльн", level: "medium" },
    { name: "Дом Кёльнский", level: "medium" },
    { name: "Карривурст", level: "medium" },
    { name: "Квашеная капуста", level: "medium" },
    { name: "Марципан", level: "medium" },
    { name: "Глювайн", level: "medium" },
    { name: "Ярмарка", level: "medium" },
    { name: "Фестиваль", level: "medium" },
    { name: "Суровость", level: "medium" },
    { name: "Дисциплина", level: "medium" },
    { name: "Пунктуальность", level: "medium" },
    { name: "Немецкий язык", level: "medium" },
    { name: "Термин", level: "medium" },
    { name: "Экзамен Б1", level: "medium" },
    { name: "Медстраховка", level: "medium" },
    { name: "Бюрократия", level: "medium" },
    { name: "Кауфланд", level: "medium" },
    { name: "Экология", level: "medium" },
    { name: "Солнечные панели", level: "medium" },
    { name: "Замок Нойшванштайн", level: "medium" },
    { name: "Рейн", level: "medium" },
    { name: "Курсы", level: "medium" },
    { name: "Рождество", level: "medium" },
    { name: "Ведьма", level: "medium" },
    { name: "Волшебник", level: "medium" },
    { name: "Книга", level: "medium" },
    { name: "Опера", level: "medium" },
    { name: "Диалог", level: "medium" },
    { name: "Бетховен", level: "medium" },
    { name: "Бах", level: "medium" },
    { name: "Бомж", level: "medium" },
    { name: "Джоб центр", level: "medium" },
    { name: "Револют", level: "medium" },

    // Сложно
    { name: "Бюратор", level: "hard" },
    { name: "Екстра Блат", level: "hard" },
    { name: "MyWay", level: "hard" },
    { name: "Steintor", level: "hard" },
    { name: "Переезд в Испанию", level: "hard" },
    { name: "Кунст", level: "hard" },
    { name: "Рейф", level: "hard" },
    { name: "Кропке", level: "hard" },
    { name: "Задержка ДБ", level: "hard" },
    { name: "Инфинити", level: "hard" },
  ],
}

const SURJIK: Category = {
  name: "Суржик",
  items: [
    // Легко
    { name: "Шо", level: "easy" },
    { name: "Пакєт", level: "easy" },
    { name: "Та нє", level: "easy" },
    { name: "Тіпа", level: "easy" },
    { name: "Чуть-чуть", level: "easy" },
    { name: "Канєшно", level: "easy" },
    { name: "Всьо", level: "easy" },
    { name: "Гдє", level: "easy" },
    { name: "Піду в магАзін", level: "easy" },
    { name: "Дєнєг нєт", level: "easy" },
    { name: "Поєхали", level: "easy" },
    { name: "Нада", level: "easy" },
    { name: "Харашо", level: "easy" },
    { name: "Нормально", level: "easy" },
    { name: "Прасті", level: "easy" },
    { name: "Хлєб", level: "easy" },
    { name: "Лампочка", level: "easy" },
    { name: "Тєлєвізор", level: "easy" },
    { name: "В смислє?", level: "easy" },
    { name: "Диви шо робе!", level: "easy" },
    { name: "Бистрєй давай", level: "easy" },
    { name: "Балкон", level: "easy" },
    { name: "Йди вже", level: "easy" },
    { name: "Їсти давай", level: "easy" },
    { name: "Телєфон", level: "easy" },
    { name: "Звонить", level: "easy" },
    { name: "Лєжу", level: "easy" },
    { name: "Спать ляжу", level: "easy" },
    { name: "А шо такоє?", level: "easy" },
    { name: "Та ти шо!", level: "easy" },

    // Средне
    { name: "Кави хочеш?", level: "medium" },
    { name: "Включи світ", level: "medium" },
    { name: "Прийшли домой", level: "medium" },
    { name: "Грієш їсти?", level: "medium" },
    { name: "Пошли гулять", level: "medium" },
    { name: "Сюди іди", level: "medium" },
    { name: "Ішо чуть-чуть", level: "medium" },
    { name: "В смислі, пізно?", level: "medium" },
    { name: "Ти шо, з дуба впав?", level: "medium" },
    { name: "На кухню", level: "medium" },
    { name: "Вдома", level: "medium" },
    { name: "Гречка", level: "medium" },
    { name: "Накривай на стіл", level: "medium" },
    { name: "Та забий", level: "medium" },
    { name: "Йому пофіг", level: "medium" },
    { name: "Хата", level: "medium" },
    { name: "Щас приду", level: "medium" },
    { name: "Куда зібрався?", level: "medium" },
    { name: "Може буть", level: "medium" },
    { name: "А я ж казала", level: "medium" },
    { name: "Сиди тихо", level: "medium" },
    { name: "Блін, та шо таке", level: "medium" },
    { name: "Та ладно", level: "medium" },
    { name: "Розказуй давай", level: "medium" },
    { name: "Пошуткував", level: "medium" },
    { name: "Сідай", level: "medium" },
    { name: "Дай водички", level: "medium" },
    { name: "Включи музику", level: "medium" },
    { name: "Гріє батарея?", level: "medium" },
    { name: "Пішов на базар", level: "medium" },

    // Сложно
    { name: "Канфєта", level: "hard" },
    { name: "Пєчєнька", level: "hard" },
    { name: "Пєчка", level: "hard" },
    { name: "Вєлік", level: "hard" },
    { name: "Паляниця", level: "hard" },
    { name: "Тормозни", level: "hard" },
    { name: "За шо?", level: "hard" },
    { name: "Та він нє винний", level: "hard" },
    { name: "Сплєтні", level: "hard" },
    { name: "Піріжок", level: "hard" },
    { name: "Немає времєні", level: "hard" },
    { name: "Воно мені надо?", level: "hard" },
    { name: "Бєз понтова", level: "hard" },
    { name: "Мєлочь", level: "hard" },
    { name: "Багажнік", level: "hard" },
    { name: "Перекус", level: "hard" },
    { name: "Пюрешка", level: "hard" },
    { name: "У мене вєлік", level: "hard" },
    { name: "Тормоз", level: "hard" },
    { name: "Вибий ковёр", level: "hard" },
    { name: "Принеси мені оце", level: "hard" },
    { name: "Хто там?", level: "hard" },
    { name: "По любому", level: "hard" },
    { name: "Куда?", level: "hard" },
    { name: "Та він норм", level: "hard" },
    { name: "Не трож", level: "hard" },
    { name: "Йди сюди, казала", level: "hard" },
    { name: "Шось є?", level: "hard" },
    { name: "Канєшно нє", level: "hard" },
    { name: "Та ну його", level: "hard" },
  ],
}

const GEOGRAPHY: Category =   {
  name: "География",
  items: [
    // Легко
    { name: "Гора", level: "easy" },
    { name: "Озеро", level: "easy" },
    { name: "Река", level: "easy" },
    { name: "Океан", level: "easy" },
    { name: "Страна", level: "easy" },
    { name: "Город", level: "easy" },
    { name: "Континент", level: "easy" },
    { name: "Карта", level: "easy" },
    { name: "Компас", level: "easy" },
    { name: "Пустыня", level: "easy" },
    { name: "Полюс", level: "easy" },
    { name: "Экватор", level: "easy" },
    { name: "Край", level: "easy" },
    { name: "Земля", level: "easy" },
    { name: "Лес", level: "easy" },
    { name: "Пляж", level: "easy" },
    { name: "Море", level: "easy" },
    { name: "Парк", level: "easy" },
    { name: "Долина", level: "easy" },
    { name: "Вулкан", level: "easy" },
    { name: "Пещера", level: "easy" },
    { name: "Побережье", level: "easy" },
    { name: "Погода", level: "easy" },
    { name: "Климaт", level: "easy" },
    { name: "Солнце", level: "easy" },
    { name: "Глобус", level: "easy" },
    { name: "Остров", level: "easy" },
    { name: "Полуостров", level: "easy" },
    { name: "Граница", level: "easy" },
    { name: "Глобус", level: "easy" },

    // Средне
    { name: "Тропики", level: "medium" },
    { name: "Арктика", level: "medium" },
    { name: "Антарктида", level: "medium" },
    { name: "Африка", level: "medium" },
    { name: "Азия", level: "medium" },
    { name: "Европа", level: "medium" },
    { name: "Австралия", level: "medium" },
    { name: "Америка", level: "medium" },
    { name: "Столица", level: "medium" },
    { name: "Местность", level: "medium" },
    { name: "Устье", level: "medium" },
    { name: "Исток", level: "medium" },
    { name: "Равнина", level: "medium" },
    { name: "Хребет", level: "medium" },
    { name: "Фьорд", level: "medium" },
    { name: "Каньон", level: "medium" },
    { name: "Архипелаг", level: "medium" },
    { name: "Пролив", level: "medium" },
    { name: "Водопад", level: "medium" },
    { name: "Цунами", level: "medium" },
    { name: "Наводнение", level: "medium" },
    { name: "Тайга", level: "medium" },
    { name: "Степь", level: "medium" },
    { name: "Саванна", level: "medium" },
    { name: "Широта", level: "medium" },
    { name: "Долгота", level: "medium" },
    { name: "Шторм", level: "medium" },
    { name: "Эрозия", level: "medium" },
    { name: "Климатический пояс", level: "medium" },
    { name: "Времена года", level: "medium" },

    // Сложно
    { name: "Мангровые леса", level: "hard" },
    { name: "Скалистые горы", level: "hard" },
    { name: "Эверест", level: "hard" },
    { name: "Гималаи", level: "hard" },
    { name: "Нил", level: "hard" },
    { name: "Амазонка", level: "hard" },
    { name: "Байкал", level: "hard" },
    { name: "Сахара", level: "hard" },
    { name: "Гоби", level: "hard" },
    { name: "Марианская впадина", level: "hard" },
    { name: "Гранд-Каньон", level: "hard" },
    { name: "Карстовая пещера", level: "hard" },
    { name: "Мезозой", level: "hard" },
    { name: "Геолог", level: "hard" },
    { name: "Магма", level: "hard" },
    { name: "Тектоническая плита", level: "hard" },
    { name: "Землетрясение", level: "hard" },
    { name: "Ветровая эрозия", level: "hard" },
    { name: "Ледник", level: "hard" },
    { name: "Ландшафт", level: "hard" },
    { name: "Меридиан", level: "hard" },
    { name: "Риф", level: "hard" },
    { name: "Биом", level: "hard" },
    { name: "Субэкваториальный", level: "hard" },
    { name: "Муссон", level: "hard" },
    { name: "Атмосфера", level: "hard" },
    { name: "Высота над уровнем моря", level: "hard" },
    { name: "Сейсмология", level: "hard" },
    { name: "Океаническое течение", level: "hard" },
    { name: "Анклав", level: "hard" },
    { name: "Эстуарий", level: "hard" },
    { name: "Тундра", level: "hard" },
    { name: "Биосфера", level: "hard" },
    { name: "Рельеф", level: "hard" },
    { name: "Цирк (горный)", level: "hard" },
    { name: "Залив", level: "hard" },
    { name: "Географическая широта", level: "hard" },
    { name: "Параллель", level: "hard" },
    { name: "Морская глубина", level: "hard" },
    { name: "Климатограмма", level: "hard" },
  ],
}

const TRAVEL: Category =   {
  name: "Путешествия",
  items: [
    // Легко
    { name: "Самолёт", level: "easy" },
    { name: "Поезд", level: "easy" },
    { name: "Чемодан", level: "easy" },
    { name: "Отпуск", level: "easy" },
    { name: "Отель", level: "easy" },
    { name: "Турист", level: "easy" },
    { name: "Пляж", level: "easy" },
    { name: "Море", level: "easy" },
    { name: "Фотоаппарат", level: "easy" },
    { name: "Билет", level: "easy" },
    { name: "Паспорт", level: "easy" },
    { name: "Аэропорт", level: "easy" },
    { name: "Сувенир", level: "easy" },
    { name: "Рюкзак", level: "easy" },
    { name: "Карта", level: "easy" },
    { name: "Гид", level: "easy" },
    { name: "Тур", level: "easy" },
    { name: "Экскурсия", level: "easy" },
    { name: "Заграница", level: "easy" },
    { name: "Купальник", level: "easy" },
    { name: "Панама", level: "easy" },
    { name: "Шлёпки", level: "easy" },
    { name: "Солнцезащитный крем", level: "easy" },
    { name: "Путёвка", level: "easy" },
    { name: "Зонт", level: "easy" },
    { name: "Плавки", level: "easy" },
    { name: "Автобус", level: "easy" },
    { name: "Гид", level: "easy" },
    { name: "Страховка", level: "easy" },
    { name: "Виза", level: "easy" },

    // Средне
    { name: "Багаж", level: "medium" },
    { name: "Рейс", level: "medium" },
    { name: "Туроператор", level: "medium" },
    { name: "Трансфер", level: "medium" },
    { name: "Хостел", level: "medium" },
    { name: "Букинг", level: "medium" },
    { name: "Апартаменты", level: "medium" },
    { name: "Навигатор", level: "medium" },
    { name: "Гугл карты", level: "medium" },
    { name: "Аренда машины", level: "medium" },
    { name: "Duty Free", level: "medium" },
    { name: "Регистрация", level: "medium" },
    { name: "Посадка", level: "medium" },
    { name: "Перелёт", level: "medium" },
    { name: "Пересадка", level: "medium" },
    { name: "Камера хранения", level: "medium" },
    { name: "Check-in", level: "medium" },
    { name: "Check-out", level: "medium" },
    { name: "Стойка регистрации", level: "medium" },
    { name: "Ручная кладь", level: "medium" },
    { name: "Перевес", level: "medium" },
    { name: "Переезд", level: "medium" },
    { name: "Граница", level: "medium" },
    { name: "Пограничник", level: "medium" },
    { name: "Декларация", level: "medium" },
    { name: "Турпакет", level: "medium" },
    { name: "Бронь", level: "medium" },
    { name: "Утренняя экскурсия", level: "medium" },
    { name: "Экскурсовод", level: "medium" },
    { name: "Карта города", level: "medium" },

    // Сложно
    { name: "Jet lag", level: "hard" },
    { name: "Культурный шок", level: "hard" },
    { name: "Дьюти-фри покупки", level: "hard" },
    { name: "Местные обычаи", level: "hard" },
    { name: "Задержка рейса", level: "hard" },
    { name: "Потеря багажа", level: "hard" },
    { name: "Couchsurfing", level: "hard" },
    { name: "Автостоп", level: "hard" },
    { name: "Тревел-блог", level: "hard" },
    { name: "Виза ран", level: "hard" },
    { name: "Тур по Европе", level: "hard" },
    { name: "Каршеринг", level: "hard" },
    { name: "Электронный билет", level: "hard" },
    { name: "Ретрит", level: "hard" },
    { name: "All-inclusive", level: "hard" },
    { name: "Last-minute", level: "hard" },
    { name: "Тур выходного дня", level: "hard" },
    { name: "Соло-тревел", level: "hard" },
    { name: "План маршрута", level: "hard" },
    { name: "Ночное путешествие", level: "hard" },
    { name: "Поездка с палаткой", level: "hard" },
    { name: "Экологичный туризм", level: "hard" },
    { name: "Местная кухня", level: "hard" },
    { name: "Волонтёрство", level: "hard" },
    { name: "Хайкинг", level: "hard" },
    { name: "Трекинг", level: "hard" },
    { name: "Дорога", level: "hard" },
    { name: "Дневник путешествий", level: "hard" },
    { name: "Аэротрен", level: "hard" },
    { name: "Тревожный чемоданчик", level: "hard" },
    { name: "Рюкзак за спиной", level: "hard" },
    { name: "Карта без интернета", level: "hard" },
    { name: "Мобильный роуминг", level: "hard" },
    { name: "Заблудился", level: "hard" },
    { name: "Жара в другой стране", level: "hard" },
    { name: "Зимовка в Азии", level: "hard" },
    { name: "Запрет на ввоз", level: "hard" },
    { name: "Проверка на таможне", level: "hard" },
    { name: "Бюджет на поездку", level: "hard" },
    { name: "Путь домой", level: "hard" },
  ],
}

const MOVIE_PHRASES: Category =   {
  name: "Киноцитаты",
  items: [
    // Легко
    { name: "Я — твой отец!", level: "easy" },
    { name: "Hasta la vista, baby.", level: "easy" },
    { name: "I’ll be back.", level: "easy" },
    { name: "Ну, погоди!", level: "easy" },
    { name: "Они могут отнять у нас свободу, но никогда — наш дух", level: "easy" },
    { name: "Куда идем мы с пяточком?", level: "easy" },
    { name: "Ушёл в себя. Вернусь нескоро.", level: "easy" },
    { name: "Шо, опять?", level: "easy" },
    { name: "Я тебя слепила из того, что было.", level: "easy" },
    { name: "Холод всегда был мне по душе", level: "easy" },
    { name: "Свободу попугаям!", level: "easy" },
    { name: "Я тучка, тучка, тучка, я вовсе не медведь.", level: "easy" },
    { name: "Щяс спою!", level: "easy" },
    { name: "Здравствуйте, я ваша тётя!", level: "easy" },
    { name: "Он улетел, но обещал вернуться...", level: "easy" },

    // Средне
    { name: "pappoy banana", level: "medium" },
    { name: "Ребята, давайте жить дружно!", level: "medium" },
    { name: "А в попугаях–то я гора-а-аздо длиннее!", level: "medium" },
    { name: "А я говорю — махнём!", level: "medium" },
    { name: "Лучший мой подарочек - это ты!", level: "medium" },
    { name: "Сам дурак!", level: "medium" },
    { name: "Я просто выгляжу как лось, а в душе я бабочка", level: "medium" },
    { name: "На помощь, Шапокляк!", level: "medium" },
    { name: "Я требую продолжения банкета!", level: "medium" },
    { name: "Не виноватая я! Он сам пришёл!", level: "medium" },
    { name: "Сладко жить – целая наука!", level: "medium" },
    { name: "Сейчас как дам!", level: "medium" },
    { name: "Я просто хотел как лучше…", level: "medium" },
    { name: "Мы украли статую Свободы... правда, маленькую, из Лас-Вегаса.", level: "medium" },
    { name: "Да пребудет с тобой Сила.", level: "medium" },
    { name: "Халк крушить!", level: "medium" },
    { name: "Люди в чёрном — мы всегда рядом.", level: "medium" },
    { name: "Хьюстон, у нас проблемы!", level: "medium" },
    { name: "Держи друзей близко, а врагов - ещё ближе.", level: "medium" },
    { name: "Первое правило бойцовского клуба-нельзя говорить о бойцовском клубе", level: "medium" },

    // Сложно
    { name: "Никогда не говори «никогда»!", level: "hard" },
    { name: "Баба Яга против!", level: "hard" },
    { name: "У вас билетик есть?", level: "hard" },
    { name: "Я подумаю об этом завтра.", level: "hard" },
    { name: "Иди своей дорогой, сталкер.", level: "hard" },
    { name: "Я слишком стар для этого дерьма.", level: "hard" },
    { name: "Меня зовут Бонд. Джеймс Бонд.", level: "hard" },
    { name: "Реально то, что осознаешь.", level: "hard" },
    { name: "Зима близко.", level: "hard" },
    { name: "Я — Пикачу!", level: "hard" },
    { name: "В чем сила брат?", level: "hard" },
    { name: "Мы все умрём!", level: "hard" },
    { name: "Давай по новой, Миша, всё х…", level: "hard" },
    { name: "Ты не пройдёшь!", level: "hard" },
    { name: "А теперь — неожиданно — бац!", level: "hard" },
    { name: "Моя прелесть…", level: "hard" },
    { name: "Мы взрослеем и праздников становится все меньше.", level: "hard" },
    { name: "Я слишком ленивый, чтобы держать на тебя злость!", level: "hard" },
    { name: "Я всегда говорю — да!", level: "hard" },
    { name: "Случайности не случайны.", level: "hard" },
    { name: "Пряники не сдаются!", level: "hard" },
    { name: "Аракис учит пониманию ножа", level: "hard" },
    { name: "Я всегда буду рядом, Мэрри Джейн", level: "hard" },
    { name: "Всех убить и сбежать? Простите эти голоса, они не то сказали.", level: "hard" },
    { name: "Куда-куда? В жопу-жопу!", level: "hard" },
  ],
}

const MEMES: Category =   {
  name: "Мемы — фразы",
  items: [
    // Легко
    { name: "А ты точно продюсер?", level: "easy" },
    { name: "Всё, я обиделась", level: "easy" },
    { name: "Это фиаско, братан", level: "easy" },
    { name: "Пацан к успеху шёл", level: "easy" },
    { name: "Ты кто такой? Давай, до свидания", level: "easy" },
    { name: "Я у мамы инженер", level: "easy" },
    { name: "Мне бы твои проблемы", level: "easy" },
    { name: "Сначала было больно, потом понравилось", level: "easy" },
    { name: "Я не понял, это что за прикол?", level: "easy" },
    { name: "Это не баг — это фича.", level: "easy" },

    // Средне
    { name: "Сильная, независимая", level: "medium" },
    { name: "Имя Ибрагим вам что нибудь говорит?", level: "medium" },
    { name: "Это база", level: "medium" },
    { name: "Всё, конец связи", level: "medium" },
    { name: "Ушёл в закат", level: "medium" },
    { name: "Где мои 17 лет?", level: "medium" },
    { name: "Звучит как вызов", level: "medium" },
    { name: "Вы кто такие, я вас не звал, идите нахер", level: "medium" },
    { name: "Я не такая, я вот такая", level: "medium" },
    { name: "Я прошла афганскую войну", level: "medium" },

    // Сложно
    { name: "Это мой гриб, я его ем!", level: "hard" },
    { name: "Тапок заминирован", level: "hard" },
    { name: "Мама, я в телевизоре!", level: "hard" },
    { name: "Легендарно, просто легендарно", level: "hard" },
    { name: "Чилловый парень", level: "hard" },
    { name: "Какой прекрасные день", level: "hard" },
    { name: "Тапать хомяка", level: "hard" },
    { name: "Вы когда нибудь мечтали стать лучшей версией себя?", level: "hard" },
    { name: "Мир сошел с ума, круглую пиццу дожать в квадратные коробки и нарезают на треугольники", level: "hard" },
    { name: "Звучит кринжово, но ладно", level: "hard" },
  ],
}

const TIKTOK: Category =   {
  name: "Фразы из ТикТока",
  items: [
    // Легко
    { name: "Ты чё такая дерзкая, а?", level: "easy" },
    { name: "Ой всё!", level: "easy" },
    { name: "Шик шак шок", level: "easy" },
    { name: "Босс кфс", level: "easy" },
    { name: "Это мой вайб", level: "easy" },
    { name: "Скуф", level: "easy" },
    { name: "Чиназез, сюда", level: "easy" },
    { name: "Девочки, это провал", level: "easy" },
    { name: "На чилле", level: "easy" },
    { name: "Телочку на веранде оу ес", level: "easy" },

    // Средне
    { name: "Прибыл Годжу Сатору", level: "medium" },
    { name: "Вы будете кушать угощения?", level: "medium" },
    { name: "Я в ахуе, давай", level: "medium" },
    { name: "Спасіба дура.", level: "medium" },
    { name: "Это не баг, это стиль", level: "medium" },
    { name: "Алё, полиция?", level: "medium" },
    { name: "Обоюдно", level: "medium" },
    { name: "Сделай красиво", level: "medium" },
    { name: "Танцуй, пока молодая", level: "medium" },
    { name: "Sorry, no money", level: "medium" },

    // Сложно
    { name: "Oh piece of candy", level: "hard" },
    { name: "Постой, а можно я с тобой?", level: "hard" },
    { name: "Плаки Плаки", level: "hard" },
    { name: "Я в моменте", level: "hard" },
    { name: "Чизабретто", level: "hard" },
    { name: "Что за кринж?", level: "hard" },
    { name: "Ты чё, тиктокер?", level: "hard" },
    { name: "Вумен момент", level: "hard" },
    { name: "Драматично вышло", level: "hard" },
    { name: "Это было сильно…", level: "hard" },
  ],
}

const CARTOONS: Category =   {
  name: "Мультики",
  items: [
    // Легко
    { name: "Шрек", level: "easy" },
    { name: "Ледниковый период", level: "easy" },
    { name: "Гадкий Я", level: "easy" },
    { name: "Холодное сердце", level: "easy" },
    { name: "Том и Джерри", level: "easy" },
    { name: "Тачки", level: "easy" },
    { name: "Лунтик", level: "easy" },
    { name: "Король Лев", level: "easy" },
    { name: "Зверополис", level: "easy" },
    { name: "Винни-Пух", level: "easy" },

    // Средне
    { name: "Смешарики", level: "medium" },
    { name: "Фиксики", level: "medium" },
    { name: "Котопёс", level: "medium" },
    { name: "Спанч Боб", level: "medium" },
    { name: "Кунг-фу Панда", level: "medium" },
    { name: "Злюки бобры", level: "medium" },
    { name: "Головоломка", level: "medium" },
    { name: "Рататуй", level: "medium" },
    { name: "Красавица и чудовище", level: "medium" },
    { name: "Русалочка", level: "medium" },

    // Сложно
    { name: "Вверх", level: "hard" },
    { name: "Душа", level: "hard" },
    { name: "Гравити Фолз", level: "hard" },
    { name: "Тайна Коко", level: "hard" },
    { name: "Город героев", level: "hard" },
    { name: "Как приручить дракона", level: "hard" },
    { name: "Кот в сапогах", level: "hard" },
    { name: "Спирит", level: "hard" },
    { name: "Труп невесты", level: "hard" },
    { name: "Валли", level: "hard" },
  ],
}

export const categories: Category[] = [
  GERMANY,
  SURJIK,
  GEOGRAPHY,
  TRAVEL,
  MOVIE_PHRASES,
  MEMES,
  TIKTOK,
  CARTOONS,
]
