import { Category, WordWithCategory } from "@/types/categories";

const GERMANY: Category = {
  name: "Германия",
  items: [
    // Легко
    { label: "Берлин", level: "easy" },
    { label: "Октоберфест", level: "easy" },
    { label: "Шницель", level: "easy" },
    { label: "Пиво", level: "easy" },
    { label: "Гитлер", level: "easy" },
    { label: "БМВ", level: "easy" },
    { label: "Ауди", level: "easy" },
    { label: "Мерседес", level: "easy" },
    { label: "Порше", level: "easy" },
    { label: "Немецкая овчарка", level: "easy" },
    { label: "Университет", level: "easy" },
    { label: "Школа", level: "easy" },
    { label: "Дождь", level: "easy" },
    { label: "Снег", level: "easy" },
    { label: "Холод", level: "easy" },
    { label: "Паспорт", level: "easy" },
    { label: "ВНЖ", level: "easy" },
    { label: "Банк", level: "easy" },
    { label: "Супермаркет", level: "easy" },
    { label: "Лидл", level: "easy" },
    { label: "Альди", level: "easy" },
    { label: "DM", level: "easy" },
    { label: "Rossmann", level: "easy" },
    { label: "Аптека", level: "easy" },
    { label: "Врач", level: "easy" },
    { label: "Поезд", level: "easy" },
    { label: "Станция", level: "easy" },
    { label: "Часы", level: "easy" },
    { label: "Озеро", level: "easy" },
    { label: "Парк", level: "easy" },
    { label: "Горы", level: "easy" },
    { label: "Лес", level: "easy" },
    { label: "Цветы", level: "easy" },
    { label: "Солнышко", level: "easy" },
    { label: "Тюльпаны", level: "easy" },
    { label: "Облака", level: "easy" },
    { label: "Документы", level: "easy" },
    { label: "Курсы", level: "easy" },
    { label: "Виза", level: "easy" },
    { label: "Беженец", level: "easy" },
    { label: "Мигрант", level: "easy" },
    { label: "Билет", level: "easy" },
    { label: "Метро", level: "easy" },
    { label: "Велосипед", level: "easy" },
    { label: "Пластик", level: "easy" },
    { label: "Возврат бутылок", level: "easy" },
    { label: "Пособие", level: "easy" },
    { label: "Бумаги", level: "easy" },
    { label: "Евро", level: "easy" },
    { label: "История", level: "easy" },

    // Средне
    { label: "Бундестаг", level: "medium" },
    { label: "Бавария", level: "medium" },
    { label: "Бранденбургские ворота", level: "medium" },
    { label: "Мюнхен", level: "medium" },
    { label: "Франкфурт", level: "medium" },
    { label: "Гамбург", level: "medium" },
    { label: "Ганновер", level: "medium" },
    { label: "Кёльн", level: "medium" },
    { label: "Дом Кёльнский", level: "medium" },
    { label: "Карривурст", level: "medium" },
    { label: "Квашеная капуста", level: "medium" },
    { label: "Марципан", level: "medium" },
    { label: "Глювайн", level: "medium" },
    { label: "Ярмарка", level: "medium" },
    { label: "Фестиваль", level: "medium" },
    { label: "Суровость", level: "medium" },
    { label: "Дисциплина", level: "medium" },
    { label: "Пунктуальность", level: "medium" },
    { label: "Немецкий язык", level: "medium" },
    { label: "Термин", level: "medium" },
    { label: "Экзамен Б1", level: "medium" },
    { label: "Медстраховка", level: "medium" },
    { label: "Бюрократия", level: "medium" },
    { label: "Кауфланд", level: "medium" },
    { label: "Экология", level: "medium" },
    { label: "Солнечные панели", level: "medium" },
    { label: "Замок Нойшванштайн", level: "medium" },
    { label: "Рейн", level: "medium" },
    { label: "Курсы", level: "medium" },
    { label: "Рождество", level: "medium" },
    { label: "Ведьма", level: "medium" },
    { label: "Волшебник", level: "medium" },
    { label: "Книга", level: "medium" },
    { label: "Опера", level: "medium" },
    { label: "Диалог", level: "medium" },
    { label: "Бетховен", level: "medium" },
    { label: "Бах", level: "medium" },
    { label: "Бомж", level: "medium" },
    { label: "Джоб центр", level: "medium" },
    { label: "Револют", level: "medium" },

    // Сложно
    { label: "Бюратор", level: "hard" },
    { label: "Екстра Блат", level: "hard" },
    { label: "MyWay", level: "hard" },
    { label: "Steintor", level: "hard" },
    { label: "Переезд в Испанию", level: "hard" },
    { label: "Кунст", level: "hard" },
    { label: "Рейф", level: "hard" },
    { label: "Кропке", level: "hard" },
    { label: "Задержка ДБ", level: "hard" },
    { label: "Инфинити", level: "hard" },
  ],
}

const SURJIK: Category = {
  name: "Суржик",
  items: [
    // Легко
    { label: "Шо", level: "easy" },
    { label: "Пакєт", level: "easy" },
    { label: "Та нє", level: "easy" },
    { label: "Тіпа", level: "easy" },
    { label: "Чуть-чуть", level: "easy" },
    { label: "Канєшно", level: "easy" },
    { label: "Всьо", level: "easy" },
    { label: "Гдє", level: "easy" },
    { label: "Піду в магАзін", level: "easy" },
    { label: "Дєнєг нєт", level: "easy" },
    { label: "Поєхали", level: "easy" },
    { label: "Нада", level: "easy" },
    { label: "Харашо", level: "easy" },
    { label: "Нормально", level: "easy" },
    { label: "Прасті", level: "easy" },
    { label: "Хлєб", level: "easy" },
    { label: "Лампочка", level: "easy" },
    { label: "Тєлєвізор", level: "easy" },
    { label: "В смислє?", level: "easy" },
    { label: "Диви шо робе!", level: "easy" },
    { label: "Бистрєй давай", level: "easy" },
    { label: "Балкон", level: "easy" },
    { label: "Йди вже", level: "easy" },
    { label: "Їсти давай", level: "easy" },
    { label: "Телєфон", level: "easy" },
    { label: "Звонить", level: "easy" },
    { label: "Лєжу", level: "easy" },
    { label: "Спать ляжу", level: "easy" },
    { label: "А шо такоє?", level: "easy" },
    { label: "Та ти шо!", level: "easy" },

    // Средне
    { label: "Кави хочеш?", level: "medium" },
    { label: "Включи світ", level: "medium" },
    { label: "Прийшли домой", level: "medium" },
    { label: "Грієш їсти?", level: "medium" },
    { label: "Пошли гулять", level: "medium" },
    { label: "Сюди іди", level: "medium" },
    { label: "Ішо чуть-чуть", level: "medium" },
    { label: "В смислі, пізно?", level: "medium" },
    { label: "Ти шо, з дуба впав?", level: "medium" },
    { label: "На кухню", level: "medium" },
    { label: "Вдома", level: "medium" },
    { label: "Гречка", level: "medium" },
    { label: "Накривай на стіл", level: "medium" },
    { label: "Та забий", level: "medium" },
    { label: "Йому пофіг", level: "medium" },
    { label: "Хата", level: "medium" },
    { label: "Щас приду", level: "medium" },
    { label: "Куда зібрався?", level: "medium" },
    { label: "Може буть", level: "medium" },
    { label: "А я ж казала", level: "medium" },
    { label: "Сиди тихо", level: "medium" },
    { label: "Блін, та шо таке", level: "medium" },
    { label: "Та ладно", level: "medium" },
    { label: "Розказуй давай", level: "medium" },
    { label: "Пошуткував", level: "medium" },
    { label: "Сідай", level: "medium" },
    { label: "Дай водички", level: "medium" },
    { label: "Включи музику", level: "medium" },
    { label: "Гріє батарея?", level: "medium" },
    { label: "Пішов на базар", level: "medium" },

    // Сложно
    { label: "Канфєта", level: "hard" },
    { label: "Пєчєнька", level: "hard" },
    { label: "Пєчка", level: "hard" },
    { label: "Вєлік", level: "hard" },
    { label: "Паляниця", level: "hard" },
    { label: "Тормозни", level: "hard" },
    { label: "За шо?", level: "hard" },
    { label: "Та він нє винний", level: "hard" },
    { label: "Сплєтні", level: "hard" },
    { label: "Піріжок", level: "hard" },
    { label: "Немає времєні", level: "hard" },
    { label: "Воно мені надо?", level: "hard" },
    { label: "Бєз понтова", level: "hard" },
    { label: "Мєлочь", level: "hard" },
    { label: "Багажнік", level: "hard" },
    { label: "Перекус", level: "hard" },
    { label: "Пюрешка", level: "hard" },
    { label: "У мене вєлік", level: "hard" },
    { label: "Тормоз", level: "hard" },
    { label: "Вибий ковёр", level: "hard" },
    { label: "Принеси мені оце", level: "hard" },
    { label: "Хто там?", level: "hard" },
    { label: "По любому", level: "hard" },
    { label: "Куда?", level: "hard" },
    { label: "Та він норм", level: "hard" },
    { label: "Не трож", level: "hard" },
    { label: "Йди сюди, казала", level: "hard" },
    { label: "Шось є?", level: "hard" },
    { label: "Канєшно нє", level: "hard" },
    { label: "Та ну його", level: "hard" },
  ],
}

const GEOGRAPHY: Category =   {
  name: "География",
  items: [
    // Легко
    { label: "Гора", level: "easy" },
    { label: "Озеро", level: "easy" },
    { label: "Река", level: "easy" },
    { label: "Океан", level: "easy" },
    { label: "Страна", level: "easy" },
    { label: "Город", level: "easy" },
    { label: "Континент", level: "easy" },
    { label: "Карта", level: "easy" },
    { label: "Компас", level: "easy" },
    { label: "Пустыня", level: "easy" },
    { label: "Полюс", level: "easy" },
    { label: "Экватор", level: "easy" },
    { label: "Край", level: "easy" },
    { label: "Земля", level: "easy" },
    { label: "Лес", level: "easy" },
    { label: "Пляж", level: "easy" },
    { label: "Море", level: "easy" },
    { label: "Парк", level: "easy" },
    { label: "Долина", level: "easy" },
    { label: "Вулкан", level: "easy" },
    { label: "Пещера", level: "easy" },
    { label: "Побережье", level: "easy" },
    { label: "Погода", level: "easy" },
    { label: "Климaт", level: "easy" },
    { label: "Солнце", level: "easy" },
    { label: "Глобус", level: "easy" },
    { label: "Остров", level: "easy" },
    { label: "Полуостров", level: "easy" },
    { label: "Граница", level: "easy" },
    { label: "Глобус", level: "easy" },

    // Средне
    { label: "Тропики", level: "medium" },
    { label: "Арктика", level: "medium" },
    { label: "Антарктида", level: "medium" },
    { label: "Африка", level: "medium" },
    { label: "Азия", level: "medium" },
    { label: "Европа", level: "medium" },
    { label: "Австралия", level: "medium" },
    { label: "Америка", level: "medium" },
    { label: "Столица", level: "medium" },
    { label: "Местность", level: "medium" },
    { label: "Устье", level: "medium" },
    { label: "Исток", level: "medium" },
    { label: "Равнина", level: "medium" },
    { label: "Хребет", level: "medium" },
    { label: "Фьорд", level: "medium" },
    { label: "Каньон", level: "medium" },
    { label: "Архипелаг", level: "medium" },
    { label: "Пролив", level: "medium" },
    { label: "Водопад", level: "medium" },
    { label: "Цунами", level: "medium" },
    { label: "Наводнение", level: "medium" },
    { label: "Тайга", level: "medium" },
    { label: "Степь", level: "medium" },
    { label: "Саванна", level: "medium" },
    { label: "Широта", level: "medium" },
    { label: "Долгота", level: "medium" },
    { label: "Шторм", level: "medium" },
    { label: "Эрозия", level: "medium" },
    { label: "Климатический пояс", level: "medium" },
    { label: "Времена года", level: "medium" },

    // Сложно
    { label: "Мангровые леса", level: "hard" },
    { label: "Скалистые горы", level: "hard" },
    { label: "Эверест", level: "hard" },
    { label: "Гималаи", level: "hard" },
    { label: "Нил", level: "hard" },
    { label: "Амазонка", level: "hard" },
    { label: "Байкал", level: "hard" },
    { label: "Сахара", level: "hard" },
    { label: "Гоби", level: "hard" },
    { label: "Марианская впадина", level: "hard" },
    { label: "Гранд-Каньон", level: "hard" },
    { label: "Карстовая пещера", level: "hard" },
    { label: "Мезозой", level: "hard" },
    { label: "Геолог", level: "hard" },
    { label: "Магма", level: "hard" },
    { label: "Тектоническая плита", level: "hard" },
    { label: "Землетрясение", level: "hard" },
    { label: "Ветровая эрозия", level: "hard" },
    { label: "Ледник", level: "hard" },
    { label: "Ландшафт", level: "hard" },
    { label: "Меридиан", level: "hard" },
    { label: "Риф", level: "hard" },
    { label: "Биом", level: "hard" },
    { label: "Субэкваториальный", level: "hard" },
    { label: "Муссон", level: "hard" },
    { label: "Атмосфера", level: "hard" },
    { label: "Высота над уровнем моря", level: "hard" },
    { label: "Сейсмология", level: "hard" },
    { label: "Океаническое течение", level: "hard" },
    { label: "Анклав", level: "hard" },
    { label: "Эстуарий", level: "hard" },
    { label: "Тундра", level: "hard" },
    { label: "Биосфера", level: "hard" },
    { label: "Рельеф", level: "hard" },
    { label: "Цирк (горный)", level: "hard" },
    { label: "Залив", level: "hard" },
    { label: "Географическая широта", level: "hard" },
    { label: "Параллель", level: "hard" },
    { label: "Морская глубина", level: "hard" },
    { label: "Климатограмма", level: "hard" },
  ],
}

const TRAVEL: Category =   {
  name: "Путешествия",
  items: [
    // Легко
    { label: "Самолёт", level: "easy" },
    { label: "Поезд", level: "easy" },
    { label: "Чемодан", level: "easy" },
    { label: "Отпуск", level: "easy" },
    { label: "Отель", level: "easy" },
    { label: "Турист", level: "easy" },
    { label: "Пляж", level: "easy" },
    { label: "Море", level: "easy" },
    { label: "Фотоаппарат", level: "easy" },
    { label: "Билет", level: "easy" },
    { label: "Паспорт", level: "easy" },
    { label: "Аэропорт", level: "easy" },
    { label: "Сувенир", level: "easy" },
    { label: "Рюкзак", level: "easy" },
    { label: "Карта", level: "easy" },
    { label: "Гид", level: "easy" },
    { label: "Тур", level: "easy" },
    { label: "Экскурсия", level: "easy" },
    { label: "Заграница", level: "easy" },
    { label: "Купальник", level: "easy" },
    { label: "Панама", level: "easy" },
    { label: "Шлёпки", level: "easy" },
    { label: "Солнцезащитный крем", level: "easy" },
    { label: "Путёвка", level: "easy" },
    { label: "Зонт", level: "easy" },
    { label: "Плавки", level: "easy" },
    { label: "Автобус", level: "easy" },
    { label: "Гид", level: "easy" },
    { label: "Страховка", level: "easy" },
    { label: "Виза", level: "easy" },

    // Средне
    { label: "Багаж", level: "medium" },
    { label: "Рейс", level: "medium" },
    { label: "Туроператор", level: "medium" },
    { label: "Трансфер", level: "medium" },
    { label: "Хостел", level: "medium" },
    { label: "Букинг", level: "medium" },
    { label: "Апартаменты", level: "medium" },
    { label: "Навигатор", level: "medium" },
    { label: "Гугл карты", level: "medium" },
    { label: "Аренда машины", level: "medium" },
    { label: "Duty Free", level: "medium" },
    { label: "Регистрация", level: "medium" },
    { label: "Посадка", level: "medium" },
    { label: "Перелёт", level: "medium" },
    { label: "Пересадка", level: "medium" },
    { label: "Камера хранения", level: "medium" },
    { label: "Check-in", level: "medium" },
    { label: "Check-out", level: "medium" },
    { label: "Стойка регистрации", level: "medium" },
    { label: "Ручная кладь", level: "medium" },
    { label: "Перевес", level: "medium" },
    { label: "Переезд", level: "medium" },
    { label: "Граница", level: "medium" },
    { label: "Пограничник", level: "medium" },
    { label: "Декларация", level: "medium" },
    { label: "Турпакет", level: "medium" },
    { label: "Бронь", level: "medium" },
    { label: "Утренняя экскурсия", level: "medium" },
    { label: "Экскурсовод", level: "medium" },
    { label: "Карта города", level: "medium" },

    // Сложно
    { label: "Jet lag", level: "hard" },
    { label: "Культурный шок", level: "hard" },
    { label: "Дьюти-фри покупки", level: "hard" },
    { label: "Местные обычаи", level: "hard" },
    { label: "Задержка рейса", level: "hard" },
    { label: "Потеря багажа", level: "hard" },
    { label: "Couchsurfing", level: "hard" },
    { label: "Автостоп", level: "hard" },
    { label: "Тревел-блог", level: "hard" },
    { label: "Виза ран", level: "hard" },
    { label: "Тур по Европе", level: "hard" },
    { label: "Каршеринг", level: "hard" },
    { label: "Электронный билет", level: "hard" },
    { label: "Ретрит", level: "hard" },
    { label: "All-inclusive", level: "hard" },
    { label: "Last-minute", level: "hard" },
    { label: "Тур выходного дня", level: "hard" },
    { label: "Соло-тревел", level: "hard" },
    { label: "План маршрута", level: "hard" },
    { label: "Ночное путешествие", level: "hard" },
    { label: "Поездка с палаткой", level: "hard" },
    { label: "Экологичный туризм", level: "hard" },
    { label: "Местная кухня", level: "hard" },
    { label: "Волонтёрство", level: "hard" },
    { label: "Хайкинг", level: "hard" },
    { label: "Трекинг", level: "hard" },
    { label: "Дорога", level: "hard" },
    { label: "Дневник путешествий", level: "hard" },
    { label: "Аэротрен", level: "hard" },
    { label: "Тревожный чемоданчик", level: "hard" },
    { label: "Рюкзак за спиной", level: "hard" },
    { label: "Карта без интернета", level: "hard" },
    { label: "Мобильный роуминг", level: "hard" },
    { label: "Заблудился", level: "hard" },
    { label: "Жара в другой стране", level: "hard" },
    { label: "Зимовка в Азии", level: "hard" },
    { label: "Запрет на ввоз", level: "hard" },
    { label: "Проверка на таможне", level: "hard" },
    { label: "Бюджет на поездку", level: "hard" },
    { label: "Путь домой", level: "hard" },
  ],
}

const MOVIE_PHRASES: Category =   {
  name: "Киноцитаты",
  items: [
    // Легко
    { label: "Я — твой отец!", level: "easy" },
    { label: "Hasta la vista, baby.", level: "easy" },
    { label: "I’ll be back.", level: "easy" },
    { label: "Ну, погоди!", level: "easy" },
    { label: "Они могут отнять у нас свободу, но никогда — наш дух", level: "easy" },
    { label: "Куда идем мы с пяточком?", level: "easy" },
    { label: "Ушёл в себя. Вернусь нескоро.", level: "easy" },
    { label: "Шо, опять?", level: "easy" },
    { label: "Я тебя слепила из того, что было.", level: "easy" },
    { label: "Холод всегда был мне по душе", level: "easy" },
    { label: "Свободу попугаям!", level: "easy" },
    { label: "Я тучка, тучка, тучка, я вовсе не медведь.", level: "easy" },
    { label: "Щяс спою!", level: "easy" },
    { label: "Здравствуйте, я ваша тётя!", level: "easy" },
    { label: "Он улетел, но обещал вернуться...", level: "easy" },

    // Средне
    { label: "pappoy banana", level: "medium" },
    { label: "Ребята, давайте жить дружно!", level: "medium" },
    { label: "А в попугаях–то я гора-а-аздо длиннее!", level: "medium" },
    { label: "А я говорю — махнём!", level: "medium" },
    { label: "Лучший мой подарочек - это ты!", level: "medium" },
    { label: "Сам дурак!", level: "medium" },
    { label: "Я просто выгляжу как лось, а в душе я бабочка", level: "medium" },
    { label: "На помощь, Шапокляк!", level: "medium" },
    { label: "Я требую продолжения банкета!", level: "medium" },
    { label: "Не виноватая я! Он сам пришёл!", level: "medium" },
    { label: "Сладко жить – целая наука!", level: "medium" },
    { label: "Сейчас как дам!", level: "medium" },
    { label: "Я просто хотел как лучше…", level: "medium" },
    { label: "Мы украли статую Свободы... правда, маленькую, из Лас-Вегаса.", level: "medium" },
    { label: "Да пребудет с тобой Сила.", level: "medium" },
    { label: "Халк крушить!", level: "medium" },
    { label: "Люди в чёрном — мы всегда рядом.", level: "medium" },
    { label: "Хьюстон, у нас проблемы!", level: "medium" },
    { label: "Держи друзей близко, а врагов - ещё ближе.", level: "medium" },
    { label: "Первое правило бойцовского клуба-нельзя говорить о бойцовском клубе", level: "medium" },

    // Сложно
    { label: "Никогда не говори «никогда»!", level: "hard" },
    { label: "Баба Яга против!", level: "hard" },
    { label: "У вас билетик есть?", level: "hard" },
    { label: "Я подумаю об этом завтра.", level: "hard" },
    { label: "Иди своей дорогой, сталкер.", level: "hard" },
    { label: "Я слишком стар для этого дерьма.", level: "hard" },
    { label: "Меня зовут Бонд. Джеймс Бонд.", level: "hard" },
    { label: "Реально то, что осознаешь.", level: "hard" },
    { label: "Зима близко.", level: "hard" },
    { label: "Я — Пикачу!", level: "hard" },
    { label: "В чем сила брат?", level: "hard" },
    { label: "Мы все умрём!", level: "hard" },
    { label: "Давай по новой, Миша, всё х…", level: "hard" },
    { label: "Ты не пройдёшь!", level: "hard" },
    { label: "А теперь — неожиданно — бац!", level: "hard" },
    { label: "Моя прелесть…", level: "hard" },
    { label: "Мы взрослеем и праздников становится все меньше.", level: "hard" },
    { label: "Я слишком ленивый, чтобы держать на тебя злость!", level: "hard" },
    { label: "Я всегда говорю — да!", level: "hard" },
    { label: "Случайности не случайны.", level: "hard" },
    { label: "Пряники не сдаются!", level: "hard" },
    { label: "Аракис учит пониманию ножа", level: "hard" },
    { label: "Я всегда буду рядом, Мэрри Джейн", level: "hard" },
    { label: "Всех убить и сбежать? Простите эти голоса, они не то сказали.", level: "hard" },
    { label: "Куда-куда? В жопу-жопу!", level: "hard" },
  ],
}

const MEMES: Category =   {
  name: "Мемы — фразы",
  items: [
    // Легко
    { label: "А ты точно продюсер?", level: "easy" },
    { label: "Всё, я обиделась", level: "easy" },
    { label: "Это фиаско, братан", level: "easy" },
    { label: "Пацан к успеху шёл", level: "easy" },
    { label: "Ты кто такой? Давай, до свидания", level: "easy" },
    { label: "Я у мамы инженер", level: "easy" },
    { label: "Мне бы твои проблемы", level: "easy" },
    { label: "Сначала было больно, потом понравилось", level: "easy" },
    { label: "Я не понял, это что за прикол?", level: "easy" },
    { label: "Это не баг — это фича.", level: "easy" },

    // Средне
    { label: "Сильная, независимая", level: "medium" },
    { label: "Имя Ибрагим вам что нибудь говорит?", level: "medium" },
    { label: "Это база", level: "medium" },
    { label: "Всё, конец связи", level: "medium" },
    { label: "Ушёл в закат", level: "medium" },
    { label: "Где мои 17 лет?", level: "medium" },
    { label: "Звучит как вызов", level: "medium" },
    { label: "Вы кто такие, я вас не звал, идите нахер", level: "medium" },
    { label: "Я не такая, я вот такая", level: "medium" },
    { label: "Я прошла афганскую войну", level: "medium" },

    // Сложно
    { label: "Это мой гриб, я его ем!", level: "hard" },
    { label: "Тапок заминирован", level: "hard" },
    { label: "Мама, я в телевизоре!", level: "hard" },
    { label: "Легендарно, просто легендарно", level: "hard" },
    { label: "Чилловый парень", level: "hard" },
    { label: "Какой прекрасные день", level: "hard" },
    { label: "Тапать хомяка", level: "hard" },
    { label: "Вы когда нибудь мечтали стать лучшей версией себя?", level: "hard" },
    { label: "Мир сошел с ума, круглую пиццу дожать в квадратные коробки и нарезают на треугольники", level: "hard" },
    { label: "Звучит кринжово, но ладно", level: "hard" },
  ],
}

const TIKTOK: Category =   {
  name: "Фразы из ТикТока",
  items: [
    // Легко
    { label: "Ты чё такая дерзкая, а?", level: "easy" },
    { label: "Ой всё!", level: "easy" },
    { label: "Шик шак шок", level: "easy" },
    { label: "Босс кфс", level: "easy" },
    { label: "Это мой вайб", level: "easy" },
    { label: "Скуф", level: "easy" },
    { label: "Чиназез, сюда", level: "easy" },
    { label: "Девочки, это провал", level: "easy" },
    { label: "На чилле", level: "easy" },
    { label: "Телочку на веранде оу ес", level: "easy" },

    // Средне
    { label: "Прибыл Годжу Сатору", level: "medium" },
    { label: "Вы будете кушать угощения?", level: "medium" },
    { label: "Я в ахуе, давай", level: "medium" },
    { label: "Спасіба дура.", level: "medium" },
    { label: "Это не баг, это стиль", level: "medium" },
    { label: "Алё, полиция?", level: "medium" },
    { label: "Обоюдно", level: "medium" },
    { label: "Сделай красиво", level: "medium" },
    { label: "Танцуй, пока молодая", level: "medium" },
    { label: "Sorry, no money", level: "medium" },

    // Сложно
    { label: "Oh piece of candy", level: "hard" },
    { label: "Постой, а можно я с тобой?", level: "hard" },
    { label: "Плаки Плаки", level: "hard" },
    { label: "Я в моменте", level: "hard" },
    { label: "Чизабретто", level: "hard" },
    { label: "Что за кринж?", level: "hard" },
    { label: "Ты чё, тиктокер?", level: "hard" },
    { label: "Вумен момент", level: "hard" },
    { label: "Драматично вышло", level: "hard" },
    { label: "Это было сильно…", level: "hard" },
  ],
}

const CARTOONS: Category =   {
  name: "Мультики",
  items: [
    // Легко
    { label: "Шрек", level: "easy" },
    { label: "Ледниковый период", level: "easy" },
    { label: "Гадкий Я", level: "easy" },
    { label: "Холодное сердце", level: "easy" },
    { label: "Том и Джерри", level: "easy" },
    { label: "Тачки", level: "easy" },
    { label: "Лунтик", level: "easy" },
    { label: "Король Лев", level: "easy" },
    { label: "Зверополис", level: "easy" },
    { label: "Винни-Пух", level: "easy" },

    // Средне
    { label: "Смешарики", level: "medium" },
    { label: "Фиксики", level: "medium" },
    { label: "Котопёс", level: "medium" },
    { label: "Спанч Боб", level: "medium" },
    { label: "Кунг-фу Панда", level: "medium" },
    { label: "Злюки бобры", level: "medium" },
    { label: "Головоломка", level: "medium" },
    { label: "Рататуй", level: "medium" },
    { label: "Красавица и чудовище", level: "medium" },
    { label: "Русалочка", level: "medium" },

    // Сложно
    { label: "Вверх", level: "hard" },
    { label: "Душа", level: "hard" },
    { label: "Гравити Фолз", level: "hard" },
    { label: "Тайна Коко", level: "hard" },
    { label: "Город героев", level: "hard" },
    { label: "Как приручить дракона", level: "hard" },
    { label: "Кот в сапогах", level: "hard" },
    { label: "Спирит", level: "hard" },
    { label: "Труп невесты", level: "hard" },
    { label: "Валли", level: "hard" },
  ],
}

export const categories: Category[] = [
  GERMANY,
  SURJIK,
  GEOGRAPHY,
  TRAVEL,
  MOVIE_PHRASES,
  MEMES,
  TIKTOK,
  CARTOONS,
]

export const getAllCategoryNames = () : string[] => {
  return categories.map((category) => category.name)
}

export const getAllWords = () : WordWithCategory[] => {
  const reducer = (acc: WordWithCategory[], category: Category) => {
    return [...acc, ...category.items.map((item) => ({
      ...item,
      categoryName: category.name,
    }))]
  }

  return categories.reduce(reducer, [])
}
